### ISSUE TITLE
Question: Where project data is saved and enabling persistent storage?

### ISSUE THREAD

**Issue by mruderman** [adam-binks/write-reason#1]
Thanks for sharing such an intriguing project. I've struggled with finding a good strategy for translating argument maps into actual manuscript outlines. The idea that it emerges from the dynamic construction of such maps is compelling, and I look forward to trying it.

I am a relatively non-technical user (at least 0% background in js or CSS). Where is the project data saved when running a locally cloned installation? It seems it is stored within each browser's local storage rather than going into the project folder itself. How can I ensure the project data persists between sessions (does clearing browser cache/cookies/etc. delete project data)?

**Comment by mruderman** [comment]
Actually, when opening Write Reason in another browser it appears that the project data does not persist.

When running a npm installation on locally cloned repository, I can upload a json data file, but I don't seem to be ale to make further iterative saves with the "Write Reason logs.json 0" button in the bottom right of the UI. Is there a way of using Write Reason with a reliable way to make iterative saves? If this repo is intended solely for the scientific reproducibility for your study, I totally respect that.

**Comment by adam-binks** [comment]
Hi, thank you! Yes, data is stored locally in your browser's [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). The project data does persist between sessions (opening and closing the tab or browser), but it is unfortunately [cleared](https://bugs.chromium.org/p/chromium/issues/detail?id=443592) when you clear your browser history+cookies. I'm open to pull requests that make a workaround for this (I am unlikely to do it myself).

In case you didn't notice, you can [use the tool online here](https://adambinks.me/write-reason/), and your data is stored in IndexedDB just the same:)

**Comment by mruderman** [comment]
Thanks for your reply. In case anyone finds this helpful, it appears that although persistent storage is not enabled by default, it can be enabled with the code below entered into a chrome/chromium based browser (not sure about firefox). Please note, according to the author of this code, **there may _not_ be a way to disable persistent storage if you use this method.** 

Note: code sourced from [here](https://web.dev/persistent-storage/#what-storage-is-protected-by-persistent-storage). I recommend you vet this method yourself, as I am not qualified to assess any theoretical (or real) security vulnerabilities or other concerns that could result from this.

Another note: Please note that it may still be possible to inadvertently delete data if the user clears the IndexedDB, history,  or cookies (I have not tested :wink: ). Instead, this workaround addresses the possibility of data being automatically erased by the chrome/chromium-based browser.

1. Open your WriteReason web app (I tested this on a local npm installation of WriteReason), but I imagine it would also work with the version hosted by @adam-binks. 
2. For this step, I recommend (neurotically) not having any other tabs open _other_ than your WriteReason web app (reduce the chance of accidentally granting persistent storage permission to another site). To access a chrome/chromium console, press F12 within the browser, find the 'console' tab, and enter the following:
```
if (navigator.storage && navigator.storage.persist) {
  const isPersisted = await navigator.storage.persist();
  console.log(`Persisted storage granted: ${isPersisted}`);
}
```
3. Press enter

Optionally: You can check to see that persistent storage permission was indeed granted with this code in the console (note it looks similar to above but is not identical). Again, only have the web app open when you engage the console:

```
if (navigator.storage && navigator.storage.persist) {
  const isPersisted = await navigator.storage.persisted();
  console.log(`Persisted storage granted: ${isPersisted}`);
}
```
That's it!
